using System;
using System.IO;

namespace RyzenTuner
{
    partial class Form1
    {
        private string _sleepMode = "SleepMode";
        private string _powerSaveMode = "PowerSaveMode";
        private string _balancedMode = "BalancedMode";
        private string _performanceMode = "PerformanceMode";
        private string _customMode = "CustomMode";

        /// <summary>
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /**
         * 返回当前应用的图标
         */
        private System.Drawing.Icon getIcon()
        {
            var stringInBase64 = "AAABAAEAYGAAAAEAIAD8lAAAFgAAACgAAABgAAAAwAAAAAEAIAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnpv+EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wEmp//8J6f/kQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSk/w4mp///Jqf//yan/3oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSm/ysmp///Jqf//yan//4nqP9VAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACen/04mp///Jqf//yan//8mp//wJqX/IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACan/4Amp///Jqf//yan//8mp///Jqf/yjOZ/wUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHv2UwAAAAAAAAAAAAAAACWm/7gmp///Jqf//yan//8mp///Jqf//yeo/28AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe/Y4AHv2vgAAAAAAAAAAK6r/Bian//Emp///Jqf//yan//8mp///Jqf//yao/+8jov8WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0/wsAe/XdAH31sgAAAAAAAAAAJKj/Rian//8mp///Jqf//yan//8mp///Jqf//yan//8mqP+bAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB99okAfPX/AHv2vgAAAAAAAAAAJqf/lCan//8mp///Jqf//yan//8mp///Jqf//yan//8mp//8I6r/JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID4JAB89foAfPX/AHz18ABm/wUrqv8GJqf/6Can//8mp///Jqf//yan//8mp///JZf9/yan//8mp///Jqj/lQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHz1oQB89f8AfPX/AHz1/wB89Hkmp/9XJqf//yan//8mp///Jqf//yan//8mp///JJb9/yOI+/8mp///Jqf/8yuq/wwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfPchAHz1/AB89f8AfPX/AHz1/wB89f8dnf3zJqf//yan//8mp///Jqf//yan//8mp///Jqf//yBd9v8ln/7/Jqf//yam/18AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAffWBAHz1/wB89f8AfPX/AHz1/weE9/8mpv//Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yBm9/8ha/f/Jqf//yan/7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA/wIAfPXgAHz1/wB89f8AfPX/AHz1/xqZ/P8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yF0+P8eUfT/I4z8/yan//Qgn/8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB99TEAfPX/AHz1/wB89f8AfPX/CIT3/yam//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yF3+f8eUfT/H1/2/yam//8nqf87AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB89m8AfPX/AHz1/wB89f8AfPX/G5v8/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yJ6+f8eUfT/HlH0/yOG+/8mpv9zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB99aoAfPX/AHz1/wB89f8Gg/f/Jqb//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yF0+P8eUfT/HlH0/x9f9v8mpf+iAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB89cwAfPX/AHz1/wB89f8Ukvr/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yBq9/8eUfT/HlH0/x5R9P8kjvvQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB89eIAfPX/AHz1/wB89f8dnf3/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//x9b9f8eUfT/HlH0/x5R9P8hdPnxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB89fcAfPX/AHz1/wB89f8jo/7/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///JJj9/x5R9P8eUfT/HlH0/x5R9P8fYfb8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB89fUAfPX/AHz1/wB89f8lpv//Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///In36/x5R9P8eUfT/HlH0/x5R9P8eV/X/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB89eEAfPX/AHz1/wB89f8lpf//Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mpv//H132/x5R9P8eUfT/HlH0/x5R9P8eUvT8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB89c4AfPX/AHz1/wB89f8io/7/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8jhvv/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUvTnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB89bMAfPX/AHz1/wB89f8dnf3/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yai/v8eWfX/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfTVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB79HgAfPX/AHz1/wB89f8Wlvv/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yJ3+f8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB79jgAfPX/AHz1/wB89f8Ni/j/Jqf//yan//8mp///Jqf//yan//8mp///JZv+/x9T9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfSgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA/wQAfPXmAHz1/wB89f8DgPb/Jab//yan//8mp///Jqf//yan//8mp///IXX5/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8dUPNpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfPWAAHz1/wB89f8AfPX/G5v8/yan//8mp///Jqf//yan//8mpf//H1f1/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8fU/UxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAevQXAHz19QB89f8AfPX/Doz5/yan//8mp///Jqf//yan//8kj/z/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9OgAQP8EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHz1gAB89f8AfPX/An/2/ySl//8mp///Jqf//xeW+/8Uevf/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x1Q9IwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHH/CQB79d8AfPX/AHz1/xaW+/8mp///H5/9/wF+9f8Be/X/GFr0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x1R8ywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB69UkAfPX/AHz1/waD9v8kpf//BoP2/wB89f8AfPX/BHb1/xxU9P8eUfT/HlH0/x5R9P8eUfT/HlD0tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAffW0AHz1/wB89f8Kh/j/AHz1/wB89f8AfPX/AHz1/wts9f8eUfT/HlH0/x5R9P8eUfT/HE/2NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgYP8IHFP0Lh1R9U8dUfRxHlD1kh5R9LMeUPS7HVH0vx5R9MweUfTMHlH0vh5R9KQfUfSOHlD0bx5S8jsgYP8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAevQwAHz1/gB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8UX/X/HlH0/x5R9P8eUfS0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBg/wgeUvI7HlD0bx9R9I4eUfSkHlH0vh5R9MweUfTMHVH0vx5Q9LseUfSzHlD1kh1R9HEdUfVPHFP0LiBg/wgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtR8hMeT/VNHlL0iR5S88UeUfT5HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT6H1L0yB5Q9HYaT/YdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHv2vgB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8CePX/G1X0/x5R9P4fU/UxAAAAAAAAAAAAAAAAAAAAABpP9h0eUPR2H1L0yB5R9PoeUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9PkeUvPFHlL0iR5P9U0bUfITAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFO8icdUfV7HlD0zh5R9P4eUfT/HlH0/x5R9P8eUfT/HlH0/x9V9P8gYvb/IXH4/yJ4+f8ifvr/I4X7/yOK+/8jivv/I4r7/yKE+v8ifPr/IXL4/yBi9v8eVPT/HlH0/x5R9P8eUfT9HlD0uyBQ80AAAAAAAAAAAAAAAAAAAAAAAHz2ygB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/C231/x5Q9LUAAAAAAAAAAAAAAAAgUPNAHlD0ux5R9P0eUfT/HlH0/x5U9P8gYvb/IXL4/yJ8+v8ihPr/I4r7/yOK+/8jivv/I4T7/yJ++v8iePn/IXD4/yBi9v8fVfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT+HlD0zh1R9XshTvInAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5P8yoeUfV+HlH00h5R9P8eUfT/HlH0/x5R9P8eUfT/H131/yFz+P8jiPv/JZz+/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mpP//JJD8/yJ4+f8eWfX/HlH0/x5R9P8fUfTAIFD0MAAAAAAAfPREAHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/w9r9XoAAAAAIFD0MB9R9MAeUfT/HlH0/x9Z9f8hd/n/JJD8/yak//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///JZz+/yOI+/8hcvj/H131/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH00h5R9X4eT/MqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFR9C8fUfSOHlH07R5R9P8eUfT/HlH0/x5R9P8eUfT/IGX3/ySN/P8mpv//Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mpf//JIn7/x9e9v8eUfT/HlH0+h1S9YIAfPXSAHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89dYdUvODHlH0+h5R9P8fYPb/I4n7/yal//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yam//8kjfz/IGX3/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH07R9R9I4hUfQvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJEntDh9S9X0eUfTyHlH0/x5R9P8eUfT/HlH0/x5R9P8gaPf/JZz+/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yam//8igPr/H1X1/xJj9f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8SY/X/Hlb1/yKC+v8mpv//Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///JZv9/yBn9/8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9PIfUPV8JEntDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgUPcgHVH0vx5R9P8eUfT/HlH0/x5R9P8eUfT/H1f1/yST/P8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///I5f9/wN69f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8DevX/JJj9/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8kk/z/H1f1/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0viBQ9yAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgU/IoHVD0jB5R9PoeUfT/HlH0/x5R9P8eUfT/HlH0/x9X9f8lnP7/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///FZT7/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/FpT7/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yWb/v8eVvX/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT6HVH0iyFO8icAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHU71Gh9R9KYeUfT9HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8hcvj/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8lpv//BYH2/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/BID2/yWm//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yFx+P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P0eUfSkH1L1GQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdUvVOHlH08R5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5S9P8fYfb/IGv3/yFx+P8ievn/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8Yl/v/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/xiX+/8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yJ6+f8hcfj/IGv3/x9h9v8fU/T/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH08B5P9U0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1R9HIeUfT9HlH0/x5R9P8eUfT/HlH0/x9b9f8iefn/JJT9/yal//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8KiPj/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wuH+P8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mpf//JZT9/yJ5+f8fW/X/HlH0/x5R9P8eUfT/HlH0/x5R9P0eUvRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH1H1Yh5R9P4eUfT/HlH0/x5R9P8gXfb/I4n7/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yOk/v8BffX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wF99f8jpP7/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///JIn7/yBd9v8eUfT/HlH0/x5R9P8eUfT+HVD0YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcUfM/HlH0+x5R9P8eUfT/HlH0/yF1+f8mpP//Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//xeW+/8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8Xl/v/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yak//8idPn/HlH0/x5R9P8eUfT/HlH0+h1P8j0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRJ/wceUfTXHlH0/x5R9P8eUfT/In/6/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//w2L+P8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8Ni/j/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///In/6/x5R9P8eUfT/HlH0/x9R9NkgYP8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5S84AeUfT/HlH0/x5R9P8eUfT/HlT0/x9Y9f8gYvb/InX5/ySS/P8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//waD9/8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8Gg/f/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8kkfz/IXT4/yBi9v8fWPX/HlT0/x5R9P8eUfT/HlH0/x5R9P8fUvV9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHFXxEh5R9fMeUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8hb/j/JaX//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//wJ+9v8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8Cf/b/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///JaX//yFu+P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfTyIFDvEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHlH0dx5R9P8eUPTLHVH0cRxP9jceUfWqHlH0/x5R9P8eUfT/HlH0/x5R9P8eVvX/JJb9/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//wF99f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8BffX/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///JJX9/x5W9f8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9aocT/Y3HVH0cR5R9MweUfT/H1H0dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHlHzlxxR8z8AAAAAIFDvEB5S88UeUfT/HlH0/x5R9P8eUfT/HlL0/yFw+P8ln/7/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//wN/9v8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8EgPb/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yWf/v8gb/j/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfTJHFXxEgAAAAAgUvY4H1H0jQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcVf8JHlHzxh5R9P8eUfT/HlH0/x5R9P8fWPX/JI/8/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//weE9/8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8Kh/j/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///I4/8/x9X9f8eUfT/HlH0/x5R9P8eUfT/HlH1xCBg/wgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wEeUfWqHlH0/x5R9P8eUfT/HlH0/yBg9v8lm/7/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//w+N+f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8Tkfr/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yWc/v8gYPb/HlH0/x5R9P8eUfT/HlH0/x5Q9KgAAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1Q82keUfT/HlH0/x5R9P8eUfT/IGb3/yWj/v8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//xyb/P8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB99f8gof7/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8lo/7/IGX3/x5R9P8eUfT/HlH0/x5R9P8eUPVmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH033IR5R9PIeUfT/HlH0/x5R9P8gY/b/JqL+/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yam//8Egfb/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wyK+P8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///JqL+/yBi9v8eUfT/HlH0/x5R9P8eUvT0HE7xJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHlD0ux5R9P8eUfT/HlH0/x9a9f8loP7/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8ZmPv/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AX71/yGh/v8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yag/v8fWvX/HlH0/x5R9P8eUfT/HlD0uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeU/REHlH0/x5R9P8eUfT/HlL0/ySS/P8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///EI75/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/F5b7/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8kkfz/HlL0/x5R9P8eUfT/HlH0/x9R80IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdUfPHHlH0/x5R9P8eUfT/IXX5/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp//cJKr/KgB79x8Ae/a8AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/AXv1/wts9LoNa/ImJKb/Kyan/9wmp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///InX5/x5R9P8eUfT/HlH0/x5R9MkAAP8BAAAAAAAAAAAAAAAAAAAAAB9S9UseUfT/HlH0/x5R9P8eVvX/JaH+/yan//8mp///Jqb//ySV/f8jgfr/IG/4/yBj9v8fXvb/IF32/yBm9/8ievn/Jqb//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//wkqP84AAAAAAAAAAAAgP8GAHz10QB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8AfPX/EmL0wQAAAAAAAAAAAAAAACSo/zgmp//8Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqb//yJ6+f8gZvf/IF32/x9e9v8gY/b/IG/4/yKA+v8klf3/Jqb//yan//8mp///JaD+/x5W9f8eUfT/HlH0/x5R9P8fUPVJAAAAAAAAAAAAAAAAAAAAAB5R87AeUfT/HlH0/x5R9P8iefn/Jqf//yWZ/f8id/n/Hlv1/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x9k9v8lmf3/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan/4gAAAAAAAAAAAAAAAAAAAAAAHz1TgB89f8AfPX/AHz1/wB89f8AfPX/AHz1/wB89f8Ma/X/HlHyPAAAAAAAAAAAAAAAAAAAAAAlqP+JJqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yWZ/f8fZPb/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/H1v1/yJ4+f8kmv3/Jqf//yF4+f8eUfT/HlH0/x5R9P8dUfWtAAAAAAAAAAAAAAAAIFX0GB5R9PoeUfT/HlH0/x5R9P8jhfv/IWz3/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8fVfT/I4L6/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqb/1SCf/wgAAAAAAAAAAAAAAAAAAAAAAIDxEgB89f4AfPX/AHz1/wB89f8AfPX/AHz1/wJ49f8cVPT/IFDvEAAAAAAAAAAAAAAAAAAAAAAgn/8IJqf/1yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mpv//IoL6/x5V9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/IWz3/yOF+/8eUfT/HlH0/x5R9P8eUfT7IFX0GAAAAAAAAAAAHlH0eB5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x9a9f8klv3/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp//2JKf/MQAAAAAAAAAAAAAAAAAAAAAAAAAAAFX/AwB89f0AfPX/AHz1/wB89f8AfPX/AHz1/xFj9f8eUfT/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKKT/LSen//Ump///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yWX/f8eW/X/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/H1H0dAAAAAAAAAAAHlH00h5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/H2L2/yWf/v8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//wlpv9TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDyFAB89f8AfPX/AHz1/wB89f8AfPX/BHb1/B1R9P8eUfT+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACeo/1Ump//8Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8lnv7/H2H2/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0zwAAAAAhTvQXHlH0/h5R9P8eUfT/HlH0/x5R9PseUfS6HVDzgh5R9OkeUfT/HlH0/x5R9P8fX/b/JaD+/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//ien/2MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH7zQQB89f8AfPX/AHz1/wB89f8Ae/X+F1z1/x5R9P8eUfT+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmqP9mJqf//ian//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///JqD+/yBd9v8eUfT/HlH0/x5R9P8eUfTpHVDzgh5Q9LseUfT8HlH0/x5R9P8eUfT/HlH0/hhV8xUdUPRZHlH0/x5R9P8eUfXzHlH0kCBQ9yAVVeoMHlD0yx5R9P8eUfT/HlH0/x9V9P8lmP3/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp//5J6b/XAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH30kQB89f8AfPX/AHz1/wB89f8LbPXhHlH0/x5R9P8eUfT+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ6b/Vian//cmp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yWZ/f8eVfT/HlH0/x5R9P8eUfT/HlH0yRdG/wsfTfchHlH0kR5R9fMeUfT/HlH0/x1S81ceUfObHlH0+h9R9I4eS/ARAAAAAAAAAAAdUfOuHlH0/x5R9P8eUfT/HlH0/yOF+/8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan/+glqf8+AAAAAAAAAAAAAAAAAAAAAB9S9HMeUPUzAAAAAAAAAAAAffU1AHz19wB89f8AfPX/AHz1/wdx9NoeUvT/HlH0/x5R9P8eUfT9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWp/z4mp//oJqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8ihPv/HlH0/x5R9P8eUfT/HlH0/x5R9aoAAAAAAAAAABxV8RIeUPSPHlH0+h5R85oeUfOaHlPzKwAAAAAAAAAAAAAAAB1Q9FkeUfT/HlH0/x5R9P8eUfT/IGP2/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqj/tSmj/xkAAAAAAAAAAAAAAAAAAAAAAAAAAB5R9NUeUfT6HVD0pRBl9J8Be/XwAHz1/wB79f4DePXoEmL06R5R9P8eUfT/HlH0/x5R9P8eUfXzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkqv8VJqf/rian//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///H2T2/x5R9P8eUfT/HlH0/x5R9P8eUPNWAAAAAAAAAAAAAAAAG1HyJh5R9JEAAAAAAAAAAAAAAAAAAAAAJEn/Bx5R9OYeUfT/HlH0/x5R9P8eUfT/JZT9/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//Ampv9fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5R9MweUfT/HlH0/x5R9P8eUfT/HVP1/x1S9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfTmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWn/2Amp//xJqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///JJL8/x5R9P8eUfT/HlH0/x5R9P8eUfTkJEn/BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHlH1ZR5R9P8eUfT/HlH0/x5R9P8gZ/f/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp//9Jqf/oiuq/xgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1P8j0eUfTxHlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8fUfTZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmpv8UJ6f/kSan//smp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yBm9/8eUfT/HlH0/x5R9P8eUfT/HVH0YQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8BH1H02R5R9P8eUfT/HlH0/x5R9P8kj/z/Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan/7Ykpv8rAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaT/YdHVD0jB9R9NkeUfT+HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUfS5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACmo/ywmp/+3Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yON/P8eUfT/HlH0/x5R9P8eUfT/HlH01gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfU/UxHlH0/x5R9P8eUfT/HlH0/x9Z9f8lpf//Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp//HJ6n/QQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfUfMpHlH0/x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9P8eUPR5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKKf/Oien/8Amp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yWl//8fWfX/HlH0/x5R9P8eUfT/HlH0/xxT9C4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeUPV/HlH0/x5R9P8eUfT/HlH0/yF5+f8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf/2SWn/0sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP8CHlH04x5R9P8eUfT/HlH0/x5R9P8eUfT/HlH0/x5R9N8bUfITAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlqP9MJqf/2San//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8id/n/HlH0/x5R9P8eUfT/HlH0/x9Q9XwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeUfTMHlH0/x5R9P8eUfT/HlH0/yST/P8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yen//Ump/+AJLb/BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH1D1SR5R9PgeUfT/HlH0/x5R9P8eUfT/HlH0/h9S9UsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM5n/BSeo/28mpv/yJqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8kkfz/HlH0/x5R9P8eUfT/HlH0/x5R9MkAAAAAAAAAAAAAAAAAAAAAAAAAACdO6w0eUfT+HlH0/x5R9P8eUfT/Hlb1/yWl//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqb/viKq/x4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFO8iceUfSHHVH00B5R9P8eUfT/HlH0/x9R9OoiVe4PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiqv8eJaf/vyan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mpv//Hlb1/x5R9P8eUfT/HlH0/x5R9P0VVeoMAAAAAAAAAAAAAAAAAAAAABxP9jceUfT/HlH0/x5R9P8eUfT/IG34/yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//4mqP9+AID/AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFR9C8fUvOvHlH0/x5R9P8eUvVnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKr/Ayan/4Amp//+Jqf//yan//8mp///Jqf//yan//8mp///Jqf//yan//8mp///IGz3/x5R9P8eUfT/HlH0/x5R9P8dUvU1AAAAAAAAAAAAAAAAAAAAAB9R9WIeUfT/HlH0/x5R9P8eUfT/I4D6/San//8mp///Jqf//yan//8mp///Jqf//yan//8mp///Jqf/9iWm/1MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHlH0Xx5R9PkeUfWrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnqP9VJqf/9ian//8mp///Jqf//yan//8mp///Jqf//yan//8mp///In/6/R5R9P8eUfT/HlH0/x5R9P8eUfRfAAAAAAAAAAAAAAAAAAAAAB9R9I0eUfT/HlH0/x5R9P8eUfXzJZ/+0Can//8mp///Jqf//yan//8mp///Jqf//yan//8np//1Jqn/RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1S81ceUfTUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJKb/Pyan//Mmp///Jqf//yan//8mp///Jqf//yan//8mp///JqD/zB5R9fMeUfT/HlH0/x5R9P8dUfSLAAAAAAAAAAAAAAAAAAAAAB5Q9LUeUfT/HlH0/x5R9PgeVfRFJqb/8ian//8mp///Jqf//yan//8mp///Jqf//yan//Ymp/89AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeUPWSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSm/z8mp//3Jqf//yan//8mp///Jqf//yan//8mp///Jqf/7h1U9EYeUfT5HlH0/x5R9P8eUfSzAAAAAAAAAAAAAAAAAAAAAB5R9MweUfT/HlH0/B5R81Uppf8fJqf//yan//8mp///Jqf//yan//8mp///Jqf//CWo/1IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbUfImAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnp/9OJqf//Can//8mp///Jqf//yan//8mp///Jqf//yen/xodUPVQHlH0+x5R9P8eUfTJAAAAAAAAAAAAAAAAAAAAAB5R9OAeUfT/HlD0dgAAAAAnqf9BJqf//yan//8mp///Jqf//yan//8mp///Jaf/bgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ6b/cCan//8mp///Jqf//yan//8mp///Jqf//yan/z0AAAAAHlD0eR5R9P8eUfPdAAAAAAAAAAAAAAAAAAAAAB5R9O8dUfOuAAD/AQAAAAAmpv9kJqf//yan//8mp///Jqf//yan//8mp/+mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACan/6Imp///Jqf//yan//8mp///Jqf//yWn/2AAAAAAAAD/AR5R87AeUfTuAAAAAAAAAAAAAAAAAAAAAB5S9N4cVfESAAAAAAAAAAAmp/+FJqf//yan//8mp///Jqf//yWn/9Mas/8KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6i/wsmp//WJqf//yan//8mp///Jqf//yen/4MAAAAAAAAAABxV8RIeUfPdAAAAAAAAAAAAAAAAAAAAAB1Q9VAAAAAAAAAAAAAAAAAlp/+dJqf//yan//8mp///Jqf/+ien/zQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkp/8xJqf/+San//8mp///Jqf//yan/5oAAAAAAAAAAAAAAAAfUvZRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmp/+wJqf//yan//8mp///Jqb/eQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJaf/fCan//8mp///Jqf//yan/60AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmp//DJqf//yan//8mp//KAKr/AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKr/Ayan/8smp///Jqf//yam/8EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmp//XJqf//yan//wkqP8yAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACil/zMmp//8Jqf//yan/9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmp//kJqf//yWm/5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmqP+SJqf//yan/+MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmp//qJqf/5yex/w0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkpP8OJqf/6Can/+kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmp//xJqf/ZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJaf/aCao/+8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmp//OQL//BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKr/Ayan/8kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlpv9FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWm/0UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            byte[] bytes = System.Convert.FromBase64String(stringInBase64);
            using(var ms = new MemoryStream(bytes)) {
                return new System.Drawing.Icon(ms);
            }
        }
        
        /// <summary>
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows 窗体设计器生成的代码

        /// <summary>
        /// 设计器支持所需的方法 - 不要修改
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.radioButton6 = new System.Windows.Forms.RadioButton();
            this.radioButton5 = new System.Windows.Forms.RadioButton();
            this.radioButton4 = new System.Windows.Forms.RadioButton();
            this.radioButton3 = new System.Windows.Forms.RadioButton();
            this.radioButton2 = new System.Windows.Forms.RadioButton();
            this.radioButton1 = new System.Windows.Forms.RadioButton();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.checkBox3 = new System.Windows.Forms.CheckBox();
            this.checkBox1 = new System.Windows.Forms.CheckBox();
            this.notifyIcon1 = new System.Windows.Forms.NotifyIcon(this.components);
            this.contextMenuStrip1 = new System.Windows.Forms.ContextMenuStrip(this.components);
            
            this.AutoModeCtrlAltShiftF1ToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            
            // Mode 1 到 4，依次是：待机模式、省电模式、平衡模式、性能模式
            this.Mode1ToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.Mode2ToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.Mode3ToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.Mode4ToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            
            this.CustomModeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.退出ToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            
            this.groupBox1.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.contextMenuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.textBox1);
            this.groupBox1.Controls.Add(this.radioButton6);
            this.groupBox1.Controls.Add(this.radioButton5);
            this.groupBox1.Controls.Add(this.radioButton4);
            this.groupBox1.Controls.Add(this.radioButton3);
            this.groupBox1.Controls.Add(this.radioButton2);
            this.groupBox1.Controls.Add(this.radioButton1);
            this.groupBox1.Location = new System.Drawing.Point(25, 21);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(706, 141);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "功率限制";
            
            // textBox1
            this.textBox1.Location = new System.Drawing.Point(583, 87);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(82, 35);
            this.textBox1.TabIndex = 6;
            this.textBox1.Text = "5-15";
            this.textBox1.TextChanged += new System.EventHandler(this.textBox1_TextChanged);

            // radioButton6
            this.radioButton6.AutoSize = true;
            this.radioButton6.Location = new System.Drawing.Point(464, 88);
            this.radioButton6.Name = "radioButton6";
            this.radioButton6.Size = new System.Drawing.Size(113, 28);
            this.radioButton6.TabIndex = 5;
            this.radioButton6.Tag = "CustomMode";
            this.radioButton6.Text = "手动模式";
            this.radioButton6.UseVisualStyleBackColor = true;
            this.radioButton6.CheckedChanged += new System.EventHandler(this.ChangeEnergyMode);
            
            // radioButton5
            this.radioButton5.AutoSize = true;
            this.radioButton5.Checked = true;
            this.radioButton5.Location = new System.Drawing.Point(227, 88);
            this.radioButton5.Name = "radioButton5";
            this.radioButton5.Size = new System.Drawing.Size(185, 28);
            this.radioButton5.TabIndex = 4;
            this.radioButton5.TabStop = true;
            this.radioButton5.Tag = "FactoryDefaultMode";
            this.radioButton5.Text = String.Format("性能模式-{0}W", this.GetPowerLimitByMode("FactoryDefaultMode"));
            this.radioButton5.UseVisualStyleBackColor = true;
            this.radioButton5.CheckedChanged += new System.EventHandler(this.ChangeEnergyMode);
            
            // radioButton4
            this.radioButton4.AutoSize = true;
            this.radioButton4.Location = new System.Drawing.Point(24, 88);
            this.radioButton4.Name = "radioButton4";
            this.radioButton4.Size = new System.Drawing.Size(185, 28);
            this.radioButton4.TabIndex = 3;
            this.radioButton4.Tag = "GamingMode";
            this.radioButton4.Text = String.Format("平衡模式-{0}W", this.GetPowerLimitByMode("GamingMode"));
            this.radioButton4.UseVisualStyleBackColor = true;
            this.radioButton4.CheckedChanged += new System.EventHandler(this.ChangeEnergyMode);

            // radioButton3
            this.radioButton3.AutoSize = true;
            this.radioButton3.Location = new System.Drawing.Point(464, 37);
            this.radioButton3.Name = "radioButton3";
            this.radioButton3.Size = new System.Drawing.Size(173, 28);
            this.radioButton3.TabIndex = 2;
            this.radioButton3.Tag = "BatteryLifeMode";
            this.radioButton3.Text = String.Format("省电模式-{0}W", this.GetPowerLimitByMode("BatteryLifeMode"));
            this.radioButton3.UseVisualStyleBackColor = true;
            this.radioButton3.CheckedChanged += new System.EventHandler(this.ChangeEnergyMode);

            // radioButton2
            this.radioButton2.AutoSize = true;
            this.radioButton2.Location = new System.Drawing.Point(227, 38);
            this.radioButton2.Name = "radioButton2";
            this.radioButton2.Size = new System.Drawing.Size(221, 28);
            this.radioButton2.TabIndex = 1;
            this.radioButton2.Tag = "ExtendedBatteryLifeMode";
            this.radioButton2.Text = String.Format("待机模式-{0}W", this.GetPowerLimitByMode("ExtendedBatteryLifeMode"));
            this.radioButton2.UseVisualStyleBackColor = true;
            this.radioButton2.CheckedChanged += new System.EventHandler(this.ChangeEnergyMode);

            // radioButton1
            this.radioButton1.AutoSize = true;
            this.radioButton1.Location = new System.Drawing.Point(24, 38);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Size = new System.Drawing.Size(197, 28);
            this.radioButton1.TabIndex = 0;
            this.radioButton1.Tag = "AutoMode";
            this.radioButton1.Text = "自动模式";
            this.radioButton1.UseVisualStyleBackColor = true;
            this.radioButton1.CheckedChanged += new System.EventHandler(this.ChangeEnergyMode);

            // groupBox3
            this.groupBox3.Controls.Add(this.checkBox3);
            this.groupBox3.Controls.Add(this.checkBox1);
            this.groupBox3.Location = new System.Drawing.Point(29, 180);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(702, 85);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "其他工具";
            // 
            // checkBox3
            // 
            this.checkBox3.AutoSize = true;
            this.checkBox3.Location = new System.Drawing.Point(261, 34);
            this.checkBox3.Name = "checkBox3";
            this.checkBox3.Size = new System.Drawing.Size(210, 28);
            this.checkBox3.TabIndex = 2;
            this.checkBox3.Text = "关闭到托盘菜单";
            this.checkBox3.UseVisualStyleBackColor = true;
            this.checkBox3.CheckedChanged += new System.EventHandler(this.checkBox3_CheckedChanged);
            // 
            // checkBox1
            // 
            this.checkBox1.AutoSize = true;
            this.checkBox1.Location = new System.Drawing.Point(21, 34);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new System.Drawing.Size(222, 28);
            this.checkBox1.TabIndex = 0;
            this.checkBox1.Text = "启用 EnergyStar";
            this.checkBox1.UseVisualStyleBackColor = true;
            this.checkBox1.CheckedChanged += new System.EventHandler(this.checkBox1_CheckedChanged);
            // 
            // notifyIcon1
            // 
            this.notifyIcon1.ContextMenuStrip = this.contextMenuStrip1;
            this.notifyIcon1.Icon = this.getIcon();
            this.notifyIcon1.Text = "RyzenTuner 运行中";
            this.notifyIcon1.Visible = true;
            this.notifyIcon1.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.notifyIcon1_MouseDoubleClick);
            // 
            // contextMenuStrip1
            // 
            this.contextMenuStrip1.ImageScalingSize = new System.Drawing.Size(32, 32);
            this.contextMenuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.AutoModeCtrlAltShiftF1ToolStripMenuItem,
            this.Mode1ToolStripMenuItem,
            this.Mode2ToolStripMenuItem,
            this.Mode3ToolStripMenuItem,
            this.Mode4ToolStripMenuItem,
            this.CustomModeToolStripMenuItem,
            this.toolStripSeparator1,
            this.退出ToolStripMenuItem});
            this.contextMenuStrip1.Name = "contextMenuStrip1";
            this.contextMenuStrip1.Size = new System.Drawing.Size(281, 276);
            this.contextMenuStrip1.Opening += new System.ComponentModel.CancelEventHandler(this.contextMenuStrip1_Opening);
         
            this.AutoModeCtrlAltShiftF1ToolStripMenuItem.CheckOnClick = true;
            this.AutoModeCtrlAltShiftF1ToolStripMenuItem.Name = "AutoModeCtrlAltShiftF1ToolStripMenuItem";
            this.AutoModeCtrlAltShiftF1ToolStripMenuItem.Size = new System.Drawing.Size(280, 38);
            this.AutoModeCtrlAltShiftF1ToolStripMenuItem.Tag = "AutoMode";
            this.AutoModeCtrlAltShiftF1ToolStripMenuItem.Text = "自动模式";
            this.AutoModeCtrlAltShiftF1ToolStripMenuItem.Click += new System.EventHandler(this.ToolStripMenuItems_Clicked);

            this.Mode1ToolStripMenuItem.CheckOnClick = true;
            this.Mode1ToolStripMenuItem.Name = "Mode1ToolStripMenuItem";
            this.Mode1ToolStripMenuItem.Size = new System.Drawing.Size(280, 38);
            this.Mode1ToolStripMenuItem.Tag = "ExtendedBatteryLifeMode";
            this.Mode1ToolStripMenuItem.Text = "待机模式";
            this.Mode1ToolStripMenuItem.Click += new System.EventHandler(this.ToolStripMenuItems_Clicked);
           
            this.Mode2ToolStripMenuItem.CheckOnClick = true;
            this.Mode2ToolStripMenuItem.Name = "Mode2ToolStripMenuItem";
            this.Mode2ToolStripMenuItem.Size = new System.Drawing.Size(280, 38);
            this.Mode2ToolStripMenuItem.Tag = "BatteryLifeMode";
            this.Mode2ToolStripMenuItem.Text = "省电模式";
            this.Mode2ToolStripMenuItem.Click += new System.EventHandler(this.ToolStripMenuItems_Clicked);

            this.Mode3ToolStripMenuItem.CheckOnClick = true;
            this.Mode3ToolStripMenuItem.Name = "Mode3ToolStripMenuItem";
            this.Mode3ToolStripMenuItem.Size = new System.Drawing.Size(280, 38);
            this.Mode3ToolStripMenuItem.Tag = "GamingMode";
            this.Mode3ToolStripMenuItem.Text = "平衡模式";
            this.Mode3ToolStripMenuItem.Click += new System.EventHandler(this.ToolStripMenuItems_Clicked);
            

            this.Mode4ToolStripMenuItem.CheckOnClick = true;
            this.Mode4ToolStripMenuItem.Name = "Mode4ToolStripMenuItem";
            this.Mode4ToolStripMenuItem.Size = new System.Drawing.Size(280, 38);
            this.Mode4ToolStripMenuItem.Tag = "FactoryDefaultMode";
            this.Mode4ToolStripMenuItem.Text = "性能模式";
            this.Mode4ToolStripMenuItem.Click += new System.EventHandler(this.ToolStripMenuItems_Clicked);

            this.CustomModeToolStripMenuItem.CheckOnClick = true;
            this.CustomModeToolStripMenuItem.Name = "CustomModeToolStripMenuItem";
            this.CustomModeToolStripMenuItem.Size = new System.Drawing.Size(280, 38);
            this.CustomModeToolStripMenuItem.Tag = "CustomMode";
            this.CustomModeToolStripMenuItem.Text = "手动模式";
            this.CustomModeToolStripMenuItem.Click += new System.EventHandler(this.ToolStripMenuItems_Clicked);
            
            // toolStripSeparator1
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(277, 6);
            // 
            // 退出ToolStripMenuItem
            // 
            this.退出ToolStripMenuItem.Name = "退出ToolStripMenuItem";
            this.退出ToolStripMenuItem.Size = new System.Drawing.Size(280, 38);
            this.退出ToolStripMenuItem.Text = "退出";
            this.退出ToolStripMenuItem.Click += new System.EventHandler(this.退出ToolStripMenuItem_Click);
            
            // 
            // timer1
            // 
            this.timer1.Enabled = true;
            this.timer1.Interval = 2048;        // 单位：毫秒
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(12F, 24F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(757, 291);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox1);
            this.Icon = this.getIcon();
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "Form1";
            this.Text = "RyzenTuner";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Form1_FormClosing);
            this.Load += new System.EventHandler(this.Form1_Load);
            this.Shown += new System.EventHandler(this.Form1_Shown);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.contextMenuStrip1.ResumeLayout(false);
            this.ResumeLayout(false);

            this._hardwareMonitor = new HardwareMonitor();
        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.RadioButton radioButton6;
        private System.Windows.Forms.RadioButton radioButton5;
        private System.Windows.Forms.RadioButton radioButton4;
        private System.Windows.Forms.RadioButton radioButton3;
        private System.Windows.Forms.RadioButton radioButton2;
        private System.Windows.Forms.RadioButton radioButton1;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.CheckBox checkBox1;
        private System.Windows.Forms.NotifyIcon notifyIcon1;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip1;
        private System.Windows.Forms.ToolStripMenuItem AutoModeCtrlAltShiftF1ToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem Mode1ToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem Mode2ToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem Mode3ToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem Mode4ToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem CustomModeToolStripMenuItem;
        private System.Windows.Forms.CheckBox checkBox3;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem 退出ToolStripMenuItem;

        private HardwareMonitor _hardwareMonitor;
    }
}

