//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyzenTuner.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RyzenTuner.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        internal static string BalancedMode {
            get {
                return ResourceManager.GetString("BalancedMode", resourceCulture);
            }
        }
        
        internal static string CustomMode {
            get {
                return ResourceManager.GetString("CustomMode", resourceCulture);
            }
        }
        
        internal static string PerformanceMode {
            get {
                return ResourceManager.GetString("PerformanceMode", resourceCulture);
            }
        }
        
        internal static string PowerSaveMode {
            get {
                return ResourceManager.GetString("PowerSaveMode", resourceCulture);
            }
        }
        
        internal static string SleepMode {
            get {
                return ResourceManager.GetString("SleepMode", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
