//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyzenTuner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RyzenTuner.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动.
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平衡.
        /// </summary>
        internal static string BalancedMode {
            get {
                return ResourceManager.GetString("BalancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动.
        /// </summary>
        internal static string CustomMode {
            get {
                return ResourceManager.GetString("CustomMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性能.
        /// </summary>
        internal static string PerformanceMode {
            get {
                return ResourceManager.GetString("PerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 省电.
        /// </summary>
        internal static string PowerSaveMode {
            get {
                return ResourceManager.GetString("PowerSaveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 睡眠.
        /// </summary>
        internal static string SleepMode {
            get {
                return ResourceManager.GetString("SleepMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string TextAbout {
            get {
                return ResourceManager.GetString("TextAbout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 严重错误.
        /// </summary>
        internal static string TextCriticalError {
            get {
                return ResourceManager.GetString("TextCriticalError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 手动功率限制必须是大于 0 的有效数字。.
        /// </summary>
        internal static string TextCustomPowerLimitInvalid {
            get {
                return ResourceManager.GetString("TextCustomPowerLimitInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用 Energy Star.
        /// </summary>
        internal static string TextEnableEnergyStar {
            get {
                return ResourceManager.GetString("TextEnableEnergyStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同一时间只允许运行一个 RyzenTuner 实例.
        /// </summary>
        internal static string TextExceptionOnlyOneProgramIsAllowedToRun {
            get {
                return ResourceManager.GetString("TextExceptionOnlyOneProgramIsAllowedToRun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 致命错误.
        /// </summary>
        internal static string TextFatalError {
            get {
                return ResourceManager.GetString("TextFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RyzenTuner 出现错误.
        /// </summary>
        internal static string TextExceptionTitle {
            get {
                return ResourceManager.GetString("TextExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string TextExit {
            get {
                return ResourceManager.GetString("TextExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 更新开机自启动设置失败。.
        /// </summary>
        internal static string TextFailedToUpdateLaunchAtLogon {
            get {
                return ResourceManager.GetString("TextFailedToUpdateLaunchAtLogon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 未找到 libryzenadj.dll！此组件为必需项。

请从官方仓库下载： https://github.com/FlyGoat/RyzenAdj.
        /// </summary>
        internal static string TextLibRyzenAdjMissing {
            get {
                return ResourceManager.GetString("TextLibRyzenAdjMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to libryzenadj.dll 版本过旧，不适用于当前版本的 RyzenTuner。

请将 libryzenadj.dll 更新到 v0.18.0 或更高版本。.
        /// </summary>
        internal static string TextLibRyzenAdjTooOld {
            get {
                return ResourceManager.GetString("TextLibRyzenAdjTooOld", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 登录时启动.
        /// </summary>
        internal static string TextLaunchAtLogon {
            get {
                return ResourceManager.GetString("TextLaunchAtLogon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 功率：限制 {power_limit} W，实际 {actual_power_limit} W.
        /// </summary>
        internal static string TextNoticeText {
            get {
                return ResourceManager.GetString("TextNoticeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU：{cpu_usage}%、{cpu_temp}℃、{cpu_freq}MHz，GPU：{gpu_usage}%.
        /// </summary>
        internal static string TextNotifyMetrics {
            get {
                return ResourceManager.GetString("TextNotifyMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他选项.
        /// </summary>
        internal static string TextOtherOptions {
            get {
                return ResourceManager.GetString("TextOtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功率限制.
        /// </summary>
        internal static string TextPowerLimit {
            get {
                return ResourceManager.GetString("TextPowerLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 部分 RyzenAdj 设置应用失败：{errors}.
        /// </summary>
        internal static string TextRyzenAdjApplyError {
            get {
                return ResourceManager.GetString("TextRyzenAdjApplyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保持唤醒.
        /// </summary>
        internal static string TextStayAwake {
            get {
                return ResourceManager.GetString("TextStayAwake", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 未处理异常：{message}.
        /// </summary>
        internal static string TextUnhandledException {
            get {
                return ResourceManager.GetString("TextUnhandledException", resourceCulture);
            }
        }
    }
}
